language: java
notifications:
  email: false
  irc:
    channels:
    - ircnet.eversible.com#katopari
    on_success: change
    use_notice: true
    skip_join: true
    template:
    - '**'
    - '%{message}'
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}'
    - 'Build details : %{build_url}'
    - '**'
after_success:
- mvn clean cobertura:cobertura coveralls:cobertura
deploy:
  provider: heroku
  api_key:
    secure: cSiXvInsBWKaCPV7zKUMDgd6MzJc8C5WYNokeM0YnweejvWD5q1hsZWAwbfLyThzSXiEwVbRnk6hOmEOgltJUlwEH3xHOran0JUrFPWqrc8dSUUXzy1/9+LVAr15SYym7d5AtsNu622qHBb6O3ezDx74d5TDLzFP/oI4haVZhSM=
  app: tenttiarkisto
  on:
    repo: Corvidian/tenttiarkisto
