language: java
notifications:
  email: false
  irc:
    channels:
    - ircnet.eversible.com#katopari
    on_success: change
    use_notice: true
    skip_join: true
    template:
    - "**"
    - "%{message}"
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}"
    - 'Build details : %{build_url}'
    - "**"
after_success:
- mvn clean cobertura:cobertura coveralls:cobertura

deploy:
	provider: heroku
		api_key:
			secure: awRwzRjrea/D6oxm6JLlMtxQsDpuNR96YTH2frPpVuDbhPM9iq3cfpxsbm6f8+6qRnzGt30ufTyo3fiBOVLSvAxo/JPykp+Vhutu6WJnb65JzGdYTFL2CQ8gB1QvlBHp3ooBQT5/l5CvsoYSwUN3JXt0Yl/56CtoW3NOBt2bNNE=
	app: tenttiarkisto
	on:
	repo: Corvidian/tenttiarkisto
